signup-ui/src/app/AppRouter.tsx
signup-ui/src/pages/SignUpPage/AccountSetup/AccountSetup.tsx

[Signup UI - Missing imports during moving repo to public](https://mosip.atlassian.net/browse/ES-676)
Import the functions and components that were missing.

ES-676: Signup UI - Missing imports during moving repo to public

---

signup-ui/README.md

[Write technical document for signup UI](https://mosip.atlassian.net/browse/ES-693)
Update README.md for signup-ui.

ES-693: write technical document for signup UI

---

docs/postman-collections/signup_001.postman_collection.json
signup-service/src/main/java/io/mosip/signup/helper/CryptoHelper.java
signup-service/src/main/java/io/mosip/signup/helper/NotificationHelper.java
signup-service/src/main/java/io/mosip/signup/services/CacheUtilService.java
signup-service/src/main/java/io/mosip/signup/services/RegistrationService.java
signup-service/src/main/java/io/mosip/signup/util/SignUpConstants.java
signup-service/src/main/resources/application-default.properties
signup-service/src/test/java/io/mosip/signup/services/RegistrationServiceTest.java
signup-service/src/test/resources/application-test.properties

1. Added updated postman collection

ES-628 ES-647

---

signup-ui/src/App.css

Fix the text box color back to the original color based on UI design, as shown. Previous PR https://github.com/mosip/esignet-signup/pull/88

ES-839: fix color

---

signup-ui/src/pages/ResetPasswordPage/ResetPasswordPage.tsx
signup-ui/src/pages/SignUpPage/SignUpPage.tsx

https://mosip.atlassian.net/jira/software/c/projects/ES/boards/92?selectedIssue=ES-741

ES-741: disable tooltips in sign up form

---

signup-ui/src/pages/shared/validation.ts

https://mosip.atlassian.net/jira/software/c/projects/ES/boards/92?selectedIssue=ES-793
Scenario 2: When password and confirm password is provided just with spaces.

ES-793 scenario 2

---

docs/esignet-signup-openapi.yaml
signup-ui/public/theme/variables.css
signup-ui/src/App.css

sync release to dev for theme name: https://github.com/mosip/esignet-signup/pull/141

Sync rename theme to common name from release

---

signup-ui/src/pages/EkycVerificationPage/TermsAndCondition/TermsAndCondition.tsx

[ES-966] making terms & condn page responsive for small screen

---

signup-integration-api/README.md
signup-integration-api/pom.xml
signup-integration-api/src/main/java/io/mosip/signup/api/dto/ProfileDto.java
signup-integration-api/src/main/java/io/mosip/signup/api/dto/ProfileResult.java
signup-integration-api/src/main/java/io/mosip/signup/api/exception/InvalidProfileException.java
signup-integration-api/src/main/java/io/mosip/signup/api/exception/ProfileException.java
signup-integration-api/src/main/java/io/mosip/signup/api/spi/ProfileRegistryPlugin.java
signup-integration-api/src/main/java/io/mosip/signup/api/util/ErrorConstants.java

https://mosip.atlassian.net/jira/software/c/projects/ES/boards/92?assignee=712020%3Ab349b58f-ce44-4c79-978c-fbe19d3bb516&selectedIssue=ES-880. No UI changes were made in this PR.

ES-880: create signup-integration-api for ProfileRegistry

---

signup-ui/public/theme/variables.css
signup-ui/src/App.css
signup-ui/src/assets/svg/check_white.svg
signup-ui/src/pages/EkycVerificationPage/EkycVerificationPage.tsx
signup-ui/src/pages/EkycVerificationPage/KycProviderList/KycProviderList.tsx
signup-ui/src/pages/EkycVerificationPage/KycProviderList/components/KycProviderCardLayout.tsx
signup-ui/src/pages/EkycVerificationPage/TermsAndCondition/TermsAndCondition.tsx
signup-ui/src/pages/EkycVerificationPage/VerificationSteps/VerificationSteps.tsx
signup-ui/src/pages/EkycVerificationPage/VideoPreview/VideoPreview.tsx
signup-ui/src/typings/types.ts

- Added search functionalities in kyc list provider page, checking only in english display name
- Remove `handleDismiss` from every component, and make it in only one component EkycVerificationPage (home page)

[ES-981] search in kycListProvider, handleDismiss in one place

---

signup-ui/public/env-config.js
signup-ui/public/index.html
signup-ui/public/lang-config.js

Move language change related code to separate folder

[ES-1115] language config for default lang

---

signup-service/src/main/resources/application-default.properties
signup-ui/src/assets/svg/chevron-up-solid.svg
signup-ui/src/components/language.tsx
signup-ui/src/components/ui/icons.tsx
signup-ui/src/pages/EkycVerificationPage/VerificationSteps/VerificationSteps.tsx
signup-ui/src/pages/EkycVerificationPage/VerificationSteps/utils/checkBrowserCompatible.ts
signup-ui/src/pages/EkycVerificationPage/VideoPreview/VideoPreview.tsx
signup-ui/src/typings/types.ts

- Dynamic key info from  i18n bundle
- Minimum browser compatibility version from signup-service
- Language dropdown up arrow icon change

[ES-973] added dynamic key info, min browser ver from server

---

signup-ui/src/pages/ResetPasswordPage/Otp/Otp.tsx
signup-ui/src/pages/SignUpPage/Otp/Otp.tsx

- modified secretDelay={200} to only secret, then it will delayed to masked the entered input

[ES-1236] modified secretDelay to secret in otp screen

---

signup-ui/README.md
signup-ui/craco.config.js
signup-ui/jest.config.js
signup-ui/package.json
signup-ui/public/mockServiceWorker.js
signup-ui/src/global.d.ts
signup-ui/src/index.tsx
signup-ui/src/mocks/browser.ts
signup-ui/src/mocks/endpoints.ts
signup-ui/src/mocks/handlers/index.ts
signup-ui/src/pages/EkycVerificationPage/VerificationSteps/utils/__tests__/checkBrowserCompatible.test.ts
signup-ui/src/pages/EkycVerificationPage/VerificationSteps/utils/checkBrowserCompatible.ts
signup-ui/src/setupTests.ts
signup-ui/src/utils/__tests__/browser.test.ts

[Browser compatibility check_Development & unit testing: Short title](https://mosip.atlassian.net/browse/ES-816)

ES-816: add browser compatibility test

---

signup-ui/src/pages/EkycVerificationPage/VerificationSteps/VerificationSteps.tsx
signup-ui/src/pages/ResetPasswordPage/Otp/Otp.tsx
signup-ui/src/pages/SignUpPage/Otp/Otp.tsx

- modified `secretDelay={200}` to only `secret`, then it will delayed to masked the entered input
- added loading spinner in verification step

[ES-1236] [ES-1306] modified secretDelay to secret in otp screen

---

signup-ui/src/mocks/endpoints.ts
signup-ui/src/mocks/handlers/index.ts
signup-ui/src/mocks/handlers/setting.ts
signup-ui/src/mocks/handlers/slot-checking.ts
signup-ui/src/pages/EkycVerificationPage/SlotChecking/SlotChecking.tsx
signup-ui/src/pages/EkycVerificationPage/SlotChecking/__tests__/SlotChecking.test.tsx
signup-ui/src/pages/EkycVerificationPage/SlotChecking/__tests__/SlotCheckingLoading.test.tsx
signup-ui/src/pages/EkycVerificationPage/SlotChecking/__tests__/SlotUnavailableAlert.test.tsx
signup-ui/src/pages/EkycVerificationPage/SlotChecking/components/SlotCheckingLoading.tsx
signup-ui/src/pages/EkycVerificationPage/SlotChecking/components/SlotUnavailableAlert.tsx
signup-ui/src/utils/test.tsx

[Development & unit testing: Short title for L2 - Slot availability check/ Loading Screen ](https://mosip.atlassian.net/browse/ES-1001)

ES-1001: add test cases for slot checking

---

signup-service/src/main/java/io/mosip/signup/controllers/WebSocketController.java
signup-ui/src/constants/routes.ts
signup-ui/src/pages/EkycVerificationPage/EkycVerificationPage.tsx
signup-ui/src/pages/EkycVerificationPage/KycProviderList/KycProviderList.tsx
signup-ui/src/pages/EkycVerificationPage/VerificationScreen/VerificationScreen.tsx
signup-ui/src/pages/shared/stompWs.ts
signup-ui/src/services/api.service.ts

- added stepCode value from request in websocketController response
- added stompjs websocket connection in verificationScreen

[ES-1160] added stompjs websocket connection in verificationScreen

---

signup-ui/src/pages/ResetPasswordPage/UserInfo/UserInfo.tsx
signup-ui/src/pages/SignUpPage/Phone/Phone.tsx

https://mosip.atlassian.net/jira/software/c/projects/ES/boards/92?assignee=712020%3Ab349b58f-ce44-4c79-978c-fbe19d3bb516&selectedIssue=ES-1170
I need to fix the issue on camdgc-dev1 environment. This issue isn't found on my dev environment, it exists nevertheless on camdgc-dev1 environment. So this PR will resolve.
Issue:

ES-1170: fix phone input as number from web-browser

---

.github/workflows/push-trigger.yml
pom.xml

[DSD-5695]

---

signup-ui/src/App.css
signup-ui/src/pages/EkycVerificationPage/VerificationScreen/VerificationScreen.tsx

[Implement the loading spinner just after slot check, before the web socket is connected](https://mosip.atlassian.net/browse/ES-1366)
- add loading indicator component

ES-1366 - Implement the loading spinner just after slot check, before the web socket is connected

---

signup-ui/public/locales/en.json
signup-ui/public/locales/km.json
signup-ui/src/pages/EkycVerificationPage/TermsAndCondition/TermsAndCondition.tsx
signup-ui/src/pages/EkycVerificationPage/VerificationScreen/VerificationScreen.tsx
signup-ui/src/utils/conversion.ts

- Clearing unnecessary console logs & methods
- Added identity verifier detail language data in current i18n bundle through i18next
- Used that updated i18n bundle to update current language data

[ES-1363] functionality to change language in between identity verification

---

signup-ui/public/theme/variables.css
signup-ui/src/App.css
signup-ui/src/pages/EkycVerificationPage/KycProviderList/KycProviderList.tsx
signup-ui/src/pages/EkycVerificationPage/KycProviderList/components/KycProviderCardLayout.tsx
signup-ui/src/pages/EkycVerificationPage/TermsAndCondition/TermsAndCondition.tsx
signup-ui/src/pages/EkycVerificationPage/VideoPreview/VideoPreview.tsx

Added configurable css in
Kyc Provider
Terms & Condn
Video Preview

[ES-1381] Added configurable css for 3 component

---

signup-ui/public/theme/variables.css
signup-ui/src/App.css
signup-ui/src/pages/EkycVerificationPage/KycProviderList/KycProviderList.tsx
signup-ui/src/pages/EkycVerificationPage/KycProviderList/components/KycProviderCardLayout.tsx
signup-ui/src/pages/EkycVerificationPage/TermsAndCondition/TermsAndCondition.tsx
signup-ui/src/pages/EkycVerificationPage/VideoPreview/VideoPreview.tsx

Added configurable css to component
Kyc Provider
Terms & Condn
Video Preview

[ES-1381] Added configurable css to component

---

signup-ui/src/pages/EkycVerificationPage/VerificationSteps/VerificationSteps.tsx

Before showing the verification steps screen, we will wait for identity-verification/initiate call to be finished, until then we will show loading screen

[ES-1364] added loading screen before kycprovider api call

---

signup-ui/public/theme/variables.css
signup-ui/src/App.css
signup-ui/src/pages/EkycVerificationPage/KycProviderList/components/KycProviderCardLayout.tsx

Reverts mosip/esignet-signup#303

Revert "[ES-1359] Fixed the tick mark issue in kyc providers list screen."

---

signup-ui/src/pages/EkycVerificationPage/IdentityVerificationStatus/IdentityVerificationStatus.tsx
signup-ui/src/pages/EkycVerificationPage/VerificationScreen/VerificationScreen.tsx
signup-ui/src/pages/EkycVerificationPage/VideoPreview/VideoPreview.tsx
signup-ui/src/pages/EkycVerificationPage/useEkycVerificationStore.tsx
signup-ui/src/react-app-env.d.ts

[MOSIP-34887](https://mosip.atlassian.net/browse/MOSIP-34887)
1. assigns stream to videoLocalStream
1. closes all tracks of the videoLocalStream when the identity verification screen mounts
[MOSIP-34887]: https://mosip.atlassian.net/browse/MOSIP-34887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MOSIP-34887

---

signup-ui/src/pages/EkycVerificationPage/TermsAndCondition/TermsAndCondition.tsx
signup-ui/src/pages/EkycVerificationPage/VerificationScreen/VerificationScreen.tsx
signup-ui/src/pages/EkycVerificationPage/VideoPreview/VideoPreview.tsx

- error handling in terms & condition
- user facing camera while ekyc verification

[ES-1356][MOSIP-35495] added error handling in term&cond, user facing camera

---

signup-ui/package.json
signup-ui/src/pages/EkycVerificationPage/VerificationSteps/utils/checkBrowserCompatible.ts

[In IOS: While checking in Chrome & Firefox with supported versions user is getting Unsupported browser error message.](https://mosip.atlassian.net/browse/ES-1550)
- identifies browser name and version using Bowser

ES-1550: improve browser compatibility check

---

signup-ui/src/pages/EkycVerificationPage/KycProviderList/KycProviderList.tsx
signup-ui/src/pages/EkycVerificationPage/KycProviderList/components/KycProviderCardLayout.tsx

[Android Device: mobile view for eKYC providers alignment is not proper](https://mosip.atlassian.net/browse/ES-1576)
- fix grid layout of the ekyc providers list\
- Items stretch to the height of the longest item

fix: fix grid items do not have the same height

---

signup-ui/src/pages/SignUpPage/Otp/Otp.tsx
signup-ui/src/pages/SignUpPage/PhoneStatus/PhoneStatus.tsx
signup-ui/src/pages/SignUpPage/useSignUpStore.tsx

Already registered user getting bypassed with first giving wrong otp.
Fixed: using separate store state for that error

[MODIFIED] second otp issue, use signup store

---

signup-integration-api/src/main/java/io/mosip/signup/api/spi/IdentityVerifierPlugin.java
signup-service/src/main/java/io/mosip/signup/services/CacheUtilService.java
signup-service/src/main/java/io/mosip/signup/services/WebSocketHandler.java
signup-service/src/main/resources/application-default.properties
signup-ui/src/pages/ResetPasswordPage/UserInfo/UserInfo.tsx
signup-ui/src/pages/shared/service.ts

- status api condition modified for correct checking
- username & fullname proper condition checking in forgot password
- changes in slot cleanup script
- changes in application-default properties

[ES-1906] [ES-1929] status api, forgot password field check, slot cleanup script, application-default

---

signup-service/src/main/java/io/mosip/signup/services/CacheUtilService.java
signup-service/src/main/java/io/mosip/signup/services/RegistrationService.java

- modifed lua cleanup script
- remove blocking of identifier from generate challenge to validate transaction

[ES-1929] [ES-1932] modified lua cleanup script, otp retrigger issue

---

deploy/init_values.yaml
deploy/keycloak/keycloak-init.sh
deploy/postgres-init.sh
deploy/prereq.sh

when we deploy signup without platform module....we should run this init script

[MOSIP-36849] added postgres init script

---

signup-ui/src/pages/EkycVerificationPage/VideoPreview/VideoPreview.tsx

remove conditonally setting permission error message with if else statement
now using setState's updater method to check if the state is changed or not

[ES-2008] modified camera permission check setState

---

api-test/pom.xml

MOSIP-38342 - updated the commons version in the POM

MOSIP-38342 - updated the commons version in the POM

---

signup-service/src/main/resources/application-default.properties

Reverts mosip/esignet-signup#405

Revert "[DSD-6445]Updated application-default.properties"

---

signup-ui/src/App.css
signup-ui/src/components/language.tsx

- remove eye icon from register form in edge browser
- remove language dropdown from ekyc video verification flow only

[ES-1991] [ES-2026] remove eye icon & language dropdown

---

api-test/src/main/resources/signup/AddIdentity/AddIdentity.yml
api-test/src/main/resources/signup/AddIdentityMock/AddIdentity.yml
api-test/src/main/resources/signup/AuthenticateUserPassword/AuthenticateUserPassword.yml
api-test/src/main/resources/signup/AuthenticateUserPasswordNegTC/AuthenticateUserPasswordNegTC.yml
api-test/src/main/resources/signup/AuthenticateUserV3/AuthenticateUser.yml
api-test/src/main/resources/signup/AuthorizationCode/AuthorizationCode.yml
api-test/src/main/resources/signup/AuthorizationCodePassword/AuthorizationCodePassword.yml
api-test/src/main/resources/signup/GenerateChallenge/GenerateChallenge.yml
api-test/src/main/resources/signup/GenerateChallengeForResetPassword/GenerateChallengeForResetPassword.yml
api-test/src/main/resources/signup/GenerateChallengeNegTC/GenerateChallengeNegTC.yml
api-test/src/main/resources/signup/GenerateToken/GenerateToken.yml
api-test/src/main/resources/signup/GetRegistrationStatus/GetRegistrationStatus.yml
api-test/src/main/resources/signup/GetRegistrationStatusForResetPassword/GetRegistrationStatusForResetPassword.yml
api-test/src/main/resources/signup/GetRegistrationStatusNegTC/GetRegistrationStatusNegTC.yml
api-test/src/main/resources/signup/RegisterUser/RegisterUser.yml
api-test/src/main/resources/signup/RegisterUserNegTC/RegisterUserNegTC.yml
api-test/src/main/resources/signup/ResetPassword/ResetPassword.yml
api-test/src/main/resources/signup/SendOtp/SendOtp.yml
api-test/src/main/resources/signup/SignUpSettings/SignUpSettings.yml
api-test/src/main/resources/signup/VerifyChallenge/VerifyChallenge.yml
api-test/src/main/resources/signup/VerifyChallengeForResetPassword/VerifyChallengeForResetPassword.yml
api-test/src/main/resources/signup/VerifyChallengeNegTC/VerifyChallengeNegTC.yml

MOSIP-38273 - copied the unique identifier from esignet repo

MOSIP-38273 - copied the unique identifier from esignet repo

---

docker-compose/README.md

[ES-2224] modified docker compose readme file

---

signup-service/src/main/java/io/mosip/signup/config/Config.java

Able to get success response when additional attribute passed in the request body

[ES-2029] Able to get success response when additional attribute passed in the request body

---

api-test/src/main/java/io/mosip/testrig/apirig/signup/testrunner/MosipTestRunner.java

- Assigning language list into an util variable

MOSIP - 39047 - Cherry picked the code from release branch

---

api-test/src/main/java/io/mosip/testrig/apirig/signup/utils/SignupUtil.java

- Added "jti" field in the sign payload for the generate token Testcases

ES-2274 - Added "jti" field in the sign payload for the generate token Testcases

---

pom.xml
signup-integration-api/pom.xml
signup-service/pom.xml
signup-with-plugins/pom.xml

ES-Release version POM updates

---

api-test/src/main/resources/signup/GenerateChallengeNegTC/GenerateChallengeNegTC.yml

Updated response for below two scenarios:
Signup_ESignet_GenerateChallengeNegTC_Empty_Regenerate_Field3_Neg
Signup_ESignet_GenerateChallengeNegTC_Null_Regenerate_Field3_Neg

ES-2301 : Updated the error codes for generate challenge api

---

api-test/src/main/resources/signup/GenerateChallengeNegTC/GenerateChallengeNegTC.yml

updated the changes made in develop branch for generatechallangeNeg api to release-1.2.x

ES-2301: cherry picked the changes from develop to release-1.2.x

---

api-test/pom.xml
api-test/testNgXmlFiles/signupPrerequisiteSuite.xml
api-test/testNgXmlFiles/signupSuite.xml

 MOSIP-41233 - Updated the pom version 

---

api-test/src/main/resources/signup/AddIdentityMock/AddIdentity.yml
api-test/src/main/resources/signup/AuthenticateUserV3/AuthenticateUser.yml
api-test/src/main/resources/signup/CompleteSignupVerificationNegTC/CompleteSignupVerificationNegTC.yml
api-test/src/main/resources/signup/IDTAuthenticationNegTC/IDTAuthenticationNegTC.yml
api-test/src/main/resources/signup/OAuthDetailsRequestV3/OAuthDetailsRequest.yml
api-test/src/main/resources/signup/PrepareSignupRedirect/PrepareSignupRedirect.yml
api-test/src/main/resources/signup/PrepareSignupRedirectNegTC/PrepareSignupRedirectNegTC.yml
api-test/src/main/resources/signup/SignupAuthorize/SignupAuthorize.yml
api-test/src/main/resources/signup/WebSocketConnection/WebSocketConnection.yml

Automated scenarios related to signup l2 flow from mastersheet

MOSIP-41339: Automated scenarios related to signup l2 flow from mastersheet

---

signup-service/src/main/java/io/mosip/signup/config/Config.java

Libraries added to plugin to make Face BIR are making XMLConverter default for POST request in singup. To overcome that we are moving the JsonConverter to first in the converter list.

[ES-2203] making json converter default for RestTemplate

---

api-test/README.md
api-test/pom.xml
deploy/signup-apitestrig/README.md

MOSIP-42410 - Updated the readme file for config property and pom file for version 1.6.1

MOSIP-42410 - Updated the readme file for config property and pom file for version 1.6.1
